package test.app.project.vo;


/**
 * 편의시설목록 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class AmenitiesVo{


	/** 편의시설식별키. */
	private int amenitiesNum;

	/** 편의시설명. */
	private String amenitiesName;

	/** 편의시설소개. */
	private String amenitiesContent;

	/** 원본파일명. */
	private String orgfilename;

	/** 저장파일명. */
	private String savefilename;

	public AmenitiesVo(int amenitiesNum, String amenitiesName, String amenitiesContent, String orgfilename,
			String savefilename) {
		super();
		this.amenitiesNum = amenitiesNum;
		this.amenitiesName = amenitiesName;
		this.amenitiesContent = amenitiesContent;
		this.orgfilename = orgfilename;
		this.savefilename = savefilename;
	}

	public AmenitiesVo() {
		
	}

	public int getAmenitiesNum() {
		return amenitiesNum;
	}

	public void setAmenitiesNum(int amenitiesNum) {
		this.amenitiesNum = amenitiesNum;
	}

	public String getAmenitiesName() {
		return amenitiesName;
	}

	public void setAmenitiesName(String amenitiesName) {
		this.amenitiesName = amenitiesName;
	}

	public String getAmenitiesContent() {
		return amenitiesContent;
	}

	public void setAmenitiesContent(String amenitiesContent) {
		this.amenitiesContent = amenitiesContent;
	}

	public String getOrgfilename() {
		return orgfilename;
	}

	public void setOrgfilename(String orgfilename) {
		this.orgfilename = orgfilename;
	}

	public String getSavefilename() {
		return savefilename;
	}

	public void setSavefilename(String savefilename) {
		this.savefilename = savefilename;
	}
	

}
