package test.app.project.vo;


/**
 * 종목(종류) 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class BEventVo{


	/** 종목식별키. */
	private int bnum;

	/** 업태. */
	private StayVo stay;

	/** 종목명. */
	private String btype;


	/**
	 * 생성자.
	 */
	public BEventVo() {
		
	}

	public BEventVo(int bnum, StayVo stay, String btype) {
		super();
		this.bnum = bnum;
		this.stay = stay;
		this.btype = btype;
	}

	public int getBnum() {
		return bnum;
	}

	public void setBnum(int bnum) {
		this.bnum = bnum;
	}

	public StayVo getStay() {
		return stay;
	}

	public void setStay(StayVo stay) {
		this.stay = stay;
	}

	public String getBtype() {
		return btype;
	}

	public void setBtype(String btype) {
		this.btype = btype;
	}


}
