package test.app.project.vo;


/**
 * 이벤트 테이블 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class EventVo{


	/** 이벤트식별키. */
	private int event_Num;

	/** 이벤트제목. */
	private String etitle;

	/** 이벤트등록일. */
	private java.sql.Date eregdate;

	/** 이벤트조회수. */
	private int ehit;

	/** 이벤트 시작일. */
	private java.sql.Date estartday;

	/** 이벤트종료일. */
	private java.sql.Date eenddate;


	/**
	 * 생성자.
	 */
	public EventVo() {
	
	}


	public EventVo(int event_Num, String etitle, java.sql.Date eregdate, int ehit, java.sql.Date estartday, java.sql.Date eenddate) {
		super();
		this.event_Num = event_Num;
		this.etitle = etitle;
		this.eregdate = eregdate;
		this.ehit = ehit;
		this.estartday = estartday;
		this.eenddate = eenddate;
	}


	public int getEventNum() {
		return event_Num;
	}


	public void setEventNum(int event_Num) {
		this.event_Num = event_Num;
	}


	public String getEtitle() {
		return etitle;
	}


	public void setEtitle(String etitle) {
		this.etitle = etitle;
	}


	public java.sql.Date getEregdate() {
		return eregdate;
	}


	public void setEregdate(java.sql.Date eregdate) {
		this.eregdate = eregdate;
	}


	public int getEhit() {
		return ehit;
	}


	public void setEhit(int ehit) {
		this.ehit = ehit;
	}


	public java.sql.Date getEstartday() {
		return estartday;
	}


	public void setEstartday(java.sql.Date estartday) {
		this.estartday = estartday;
	}


	public java.sql.Date getEenddate() {
		return eenddate;
	}


	public void setEenddate(java.sql.Date eenddate) {
		this.eenddate = eenddate;
	}



}
