package test.app.project.vo;


/**
 * 업소편의시설 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class HouseintroVo{


	/** 업소편의시설식별키. */
	private int houseIntroNum;

	/** 업소테이블. */
	private int house_num;

	/** 편의시설목록. */
	private int amenities_num;

	/**
	 * 생성자.
	 */
	public HouseintroVo() {
	}

	public HouseintroVo(int houseIntroNum, int house_num, int amenities_num) {
		super();
		this.houseIntroNum = houseIntroNum;
		this.house_num = house_num;
		this.amenities_num = amenities_num;
	}

	public int getHouseIntroNum() {
		return houseIntroNum;
	}

	public void setHouseIntroNum(int houseIntroNum) {
		this.houseIntroNum = houseIntroNum;
	}

	public int getHouse_num() {
		return house_num;
	}

	public void setHouse_num(int house_num) {
		this.house_num = house_num;
	}

	public int getAmenities_num() {
		return amenities_num;
	}

	public void setAmenities_num(int amenities_num) {
		this.amenities_num = amenities_num;
	}


}
