package test.app.project.vo;


/**
 * 결제테이블 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class PaymentVo {


	/** 결제번호. */
	private int payNum;

	/** 예약테이블. */
	private int booking_num;

	/** 쿠폰. */
	private int coupon_num;

	/** 최종결제금액. */
	private int pay;

	/** 결제날짜. */
	private java.sql.Date payDay;

	/** 결제수단. */
	private String paymentType;

	/**
	 * 생성자.
	 */
	public PaymentVo() {
	}

	public PaymentVo(int payNum, int booking_num, int coupon_num, int pay, java.sql.Date payDay, String paymentType) {
		super();
		this.payNum = payNum;
		this.booking_num = booking_num;
		this.coupon_num = coupon_num;
		this.pay = pay;
		this.payDay = payDay;
		this.paymentType = paymentType;
	}

	public int getPayNum() {
		return payNum;
	}

	public void setPayNum(int payNum) {
		this.payNum = payNum;
	}

	public int getBooking_num() {
		return booking_num;
	}

	public void setBooking_num(int booking_num) {
		this.booking_num = booking_num;
	}

	public int getCoupon_num() {
		return coupon_num;
	}

	public void setCoupon_num(int coupon_num) {
		this.coupon_num = coupon_num;
	}

	public int getPay() {
		return pay;
	}

	public void setPay(int pay) {
		this.pay = pay;
	}

	public java.sql.Date getPayDay() {
		return payDay;
	}

	public void setPayDay(java.sql.Date payDay) {
		this.payDay = payDay;
	}

	public String getPaymentType() {
		return paymentType;
	}

	public void setPaymentType(String paymentType) {
		this.paymentType = paymentType;
	}


}
