package test.app.project.vo;


/**
 * Q&A게시판 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class QnaboardVo {


	/** 문의번호. */
	private int qnaNum;

	/** 회원테이블. */
	private String mid;

	/** Q&A카테고리. */
	private int qna_category_num;

	/** 문의제목. */
	private String qnaTitle;

	/** 문의내용. */
	private String qnaContent;

	/** 답변. */
	private String anwser;

	/** 문의작성일. */
	private java.sql.Date qnaDate;

	/** 답변작성일. */
	private java.sql.Date anwserDate;

	/**
	 * 생성자.
	 */
	public QnaboardVo() {
	}

	public QnaboardVo(int qnaNum, String mid, int qna_category_num, String qnaTitle, String qnaContent, String anwser,
			java.sql.Date qnaDate, java.sql.Date anwserDate) {
		super();
		this.qnaNum = qnaNum;
		this.mid = mid;
		this.qna_category_num = qna_category_num;
		this.qnaTitle = qnaTitle;
		this.qnaContent = qnaContent;
		this.anwser = anwser;
		this.qnaDate = qnaDate;
		this.anwserDate = anwserDate;
	}

	public int getQnaNum() {
		return qnaNum;
	}

	public void setQnaNum(int qnaNum) {
		this.qnaNum = qnaNum;
	}

	public String getMid() {
		return mid;
	}

	public void setMid(String mid) {
		this.mid = mid;
	}

	public int getQna_category_num() {
		return qna_category_num;
	}

	public void setQna_category_num(int qna_category_num) {
		this.qna_category_num = qna_category_num;
	}

	public String getQnaTitle() {
		return qnaTitle;
	}

	public void setQnaTitle(String qnaTitle) {
		this.qnaTitle = qnaTitle;
	}

	public String getQnaContent() {
		return qnaContent;
	}

	public void setQnaContent(String qnaContent) {
		this.qnaContent = qnaContent;
	}

	public String getAnwser() {
		return anwser;
	}

	public void setAnwser(String anwser) {
		this.anwser = anwser;
	}

	public java.sql.Date getQnaDate() {
		return qnaDate;
	}

	public void setQnaDate(java.sql.Date qnaDate) {
		this.qnaDate = qnaDate;
	}

	public java.sql.Date getAnwserDate() {
		return anwserDate;
	}

	public void setAnwserDate(java.sql.Date anwserDate) {
		this.anwserDate = anwserDate;
	}

}
