package test.app.project.vo;

/**
 * 리뷰이미지 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ReiewImgVo{


	/** 리뷰이미지식별번호. */
	private int reviewImgNum;

	/** 후기게시판. */
	private int review_num;

	/** 리뷰이미지원본명. */
	private String reviewOrgName;

	/** 리뷰이미지저장명. */
	private String reviewSaveName;

	/**
	 * 생성자.
	 */
	public ReiewImgVo() {
	}

	public ReiewImgVo(int reviewImgNum, int review_num, String reviewOrgName, String reviewSaveName) {
		super();
		this.reviewImgNum = reviewImgNum;
		this.review_num = review_num;
		this.reviewOrgName = reviewOrgName;
		this.reviewSaveName = reviewSaveName;
	}

	public int getReviewImgNum() {
		return reviewImgNum;
	}

	public void setReviewImgNum(int reviewImgNum) {
		this.reviewImgNum = reviewImgNum;
	}

	public int getReview_num() {
		return review_num;
	}

	public void setReview_num(int review_num) {
		this.review_num = review_num;
	}

	public String getReviewOrgName() {
		return reviewOrgName;
	}

	public void setReviewOrgName(String reviewOrgName) {
		this.reviewOrgName = reviewOrgName;
	}

	public String getReviewSaveName() {
		return reviewSaveName;
	}

	public void setReviewSaveName(String reviewSaveName) {
		this.reviewSaveName = reviewSaveName;
	}

}
