package test.app.project.vo;


/**
 * 후기게시판 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ReviewVo {


	/** 후기식별키. */
	private int reviewNum;

	/** 객실정보. */
	private int room_num;

	/** 회원테이블. */
	private String mid;

	/** 리뷰제목. */
	private String reviewTitle;

	/** 리뷰내용. */
	private String reviewContent;

	/** 후기작성일. */
	private java.sql.Date reviewDate;

	/** 친절도. */
	private int kindness;

	/** 청결도. */
	private int clean;

	/** 편의성. */
	private int convenience;


	/**
	 * 생성자.
	 */
	public ReviewVo() {
		
	}


	public ReviewVo(int reviewNum, int room_num, String mid, String reviewTitle, String reviewContent,
			java.sql.Date reviewDate, int kindness, int clean, int convenience) {
		super();
		this.reviewNum = reviewNum;
		this.room_num = room_num;
		this.mid = mid;
		this.reviewTitle = reviewTitle;
		this.reviewContent = reviewContent;
		this.reviewDate = reviewDate;
		this.kindness = kindness;
		this.clean = clean;
		this.convenience = convenience;
	}


	public int getReviewNum() {
		return reviewNum;
	}


	public void setReviewNum(int reviewNum) {
		this.reviewNum = reviewNum;
	}


	public int getRoom_num() {
		return room_num;
	}


	public void setRoom_num(int room_num) {
		this.room_num = room_num;
	}


	public String getMid() {
		return mid;
	}


	public void setMid(String mid) {
		this.mid = mid;
	}


	public String getReviewTitle() {
		return reviewTitle;
	}


	public void setReviewTitle(String reviewTitle) {
		this.reviewTitle = reviewTitle;
	}


	public String getReviewContent() {
		return reviewContent;
	}


	public void setReviewContent(String reviewContent) {
		this.reviewContent = reviewContent;
	}


	public java.sql.Date getReviewDate() {
		return reviewDate;
	}


	public void setReviewDate(java.sql.Date reviewDate) {
		this.reviewDate = reviewDate;
	}


	public int getKindness() {
		return kindness;
	}


	public void setKindness(int kindness) {
		this.kindness = kindness;
	}


	public int getClean() {
		return clean;
	}


	public void setClean(int clean) {
		this.clean = clean;
	}


	public int getConvenience() {
		return convenience;
	}


	public void setConvenience(int convenience) {
		this.convenience = convenience;
	}

}
