package test.app.project.vo;


/**
 * 객실이미지 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class RoomsImgVo {


	/** 객실이미지식별키. */
	private int roomsImgNum;

	/** 객실정보. */
	private int room_num;

	/** 객실이미지원본명. */
	private String roomOrgName;

	/** 객실이미지저장명. */
	private String roomSaveName;

	/**
	 * 생성자.
	 */
	public RoomsImgVo() {
	}

	public RoomsImgVo(int roomsImgNum, int room_num, String roomOrgName, String roomSaveName) {
		super();
		this.roomsImgNum = roomsImgNum;
		this.room_num = room_num;
		this.roomOrgName = roomOrgName;
		this.roomSaveName = roomSaveName;
	}

	public int getRoomsImgNum() {
		return roomsImgNum;
	}

	public void setRoomsImgNum(int roomsImgNum) {
		this.roomsImgNum = roomsImgNum;
	}

	public int getRoom_num() {
		return room_num;
	}

	public void setRoom_num(int room_num) {
		this.room_num = room_num;
	}

	public String getRoomOrgName() {
		return roomOrgName;
	}

	public void setRoomOrgName(String roomOrgName) {
		this.roomOrgName = roomOrgName;
	}

	public String getRoomSaveName() {
		return roomSaveName;
	}

	public void setRoomSaveName(String roomSaveName) {
		this.roomSaveName = roomSaveName;
	}

}
