package test.app.project.vo;

/**
 * 객실정보 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class RoomsVo{

	/** 방식별번호. */
	private int roomNum;

	/** 업소테이블. */
	private int house_num;

	/** 객실명. */
	private String roomname;

	/** 객실가격. */
	private int roomPrise;

	/** 객실정보. */
	private String roomInfo;

	/** 룸체크인. */
	private int roomCheck;

	/** 최대인원. */
	private int maxPersonnel;


	/**
	 * 생성자.
	 */
	public RoomsVo() {

	}


	public RoomsVo(int roomNum, int house_num, String roomname, int roomPrise, String roomInfo, int roomCheck,
			int maxPersonnel) {
		super();
		this.roomNum = roomNum;
		this.house_num = house_num;
		this.roomname = roomname;
		this.roomPrise = roomPrise;
		this.roomInfo = roomInfo;
		this.roomCheck = roomCheck;
		this.maxPersonnel = maxPersonnel;
	}


	public int getRoomNum() {
		return roomNum;
	}


	public void setRoomNum(int roomNum) {
		this.roomNum = roomNum;
	}


	public int getHouse_num() {
		return house_num;
	}


	public void setHouse_num(int house_num) {
		this.house_num = house_num;
	}


	public String getRoomname() {
		return roomname;
	}


	public void setRoomname(String roomname) {
		this.roomname = roomname;
	}


	public int getRoomPrise() {
		return roomPrise;
	}


	public void setRoomPrise(int roomPrise) {
		this.roomPrise = roomPrise;
	}


	public String getRoomInfo() {
		return roomInfo;
	}


	public void setRoomInfo(String roomInfo) {
		this.roomInfo = roomInfo;
	}


	public int getRoomCheck() {
		return roomCheck;
	}


	public void setRoomCheck(int roomCheck) {
		this.roomCheck = roomCheck;
	}


	public int getMaxPersonnel() {
		return maxPersonnel;
	}


	public void setMaxPersonnel(int maxPersonnel) {
		this.maxPersonnel = maxPersonnel;
	}

}
